### ISSUE TITLE
Migrate away from geoplumber

### ISSUE THREAD

**Issue by LydiaFrance** [tgve/eAtlas#93]

**Comment by layik** [comment]
Just to clarify here, this is based on the new work in https://github.com/tgve/tgver package. Where instead of running JS tools, we rely on a bundled "build" outside the R package. For anything that has any custom React component passed to the `leftSidebarContent` API/parameter, then we do need JS builds and that in R is done under `geoplumber` R package.

**Comment by layik** [comment]
Related to #92 in a way.

**Comment by rolyp** [comment]
@layik Yes I think some of these issues will turn out to overlap a bit -- we can refine them as we go forward. Starting with #92 sounds like the best plan.

**Comment by layik** [comment]
Can move it to another repo but no longer applies to the npm package.
